spring.application.name=backend-sp
server.port=${PORT:8080}

# --- LOGS ---
logging.level.root=INFO

# --- MONGODB ---
# La URI completa la pondremos en Railway
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=plant-monitor
spring.data.mongodb.auto-index-creation=true

# --- INFLUXDB CLOUD ---
influxdb.url=${INFLUX_URL}
influxdb.token=${INFLUX_TOKEN}
influxdb.org=${INFLUX_ORG}
influxdb.bucket=${INFLUX_BUCKET}

# --- MQTT HIVEMQ ---
mqtt.broker.url=${MQTT_URL}
mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}
mqtt.client.id=${MQTT_CLIENT_ID}
mqtt.topic=planta/+/lecturas

# --- EMAIL ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================================
# 7. UMBRALES PARA LÓGICA DE ADVISOR (KPIs)
# ===============================================

# --- Humedad Ambiental (DHT11) ---
device.thresholds.humidity.min=35
device.thresholds.humidity.max=100

# --- Humedad de Suelo (Sensor Capacitivo/Resistivo) ---
# Si baja de 35%, se considera CRÍTICO y activa riego
device.thresholds.humiditySoil.min=35
device.thresholds.humiditySoil.max=100

# --- Temperatura (DHT11) ---
device.thresholds.temperature.max=38.0
device.thresholds.temperature.min=-10.0

# --- Luz (BH1750) ---
device.thresholds.light.min=200
device.thresholds.light.max=10000